[web]
binding = "127.0.0.1"  # 要绑定的网卡IP地址，默认127.0.0.1
port = 5800                 # 配置web服务端口，如果不配置默认就是8080端口

# web中间件配置
[web.middlewares]
compression = { enable = true }  # 开启压缩中间件
logger = { enable = true }       # 开启日志中间件
catch_panic = { enable = true }  # 捕获handler产生的panic
limit_payload = { enable = true, body_limit = "5MB" } # 限制请求体大小
timeout_request = { enable = true, timeout = 60000 }  # 请求超时时间60s


#[sqlx]
#uri = "mysql://root:1234@127.0.0.1:3306/bs_desktop?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true"
#min_connections = 1                                  # 连接池的最小连接数，默认值为1
#max_connections = 10                                 # 连接池的最大连接数，默认值为10
#acquire_timeout = 30000                              # 占用连接超时时间，单位毫秒，默认30s
#idle_timeout = 600000                                # 连接空闲时间，单位毫秒，默认10min
#connect_timeout = 1800000                            # 连接的最大存活时间，单位毫秒，默认30min
